import { loadDatabaseUrl } from "@my-pet-care/service-config";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool } from "pg";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/** Folder of SQL migrations generated by `drizzle-kit generate` (committed under this package). */
export const migrationsFolder = path.join(packageRoot, "drizzle");

/**
 * Apply pending drizzle-kit migrations to the database at `databaseUrl`.
 * Used by the `db:migrate` script and by persistence tests.
 */
export async function applyMigrations(databaseUrl: string): Promise<void> {
  const pool = new Pool({ connectionString: databaseUrl });
  try {
    const db = drizzle({ client: pool });
    await migrate(db, { migrationsFolder });
  } finally {
    await pool.end();
  }
}

async function main(): Promise<void> {
  const databaseUrl = await loadDatabaseUrl("ownerPetManager");
  await applyMigrations(databaseUrl);
}

const entry = process.argv[1];
const isDirectRun =
  entry !== undefined && pathToFileURL(path.resolve(entry)).href === import.meta.url;

if (isDirectRun) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exitCode = 1;
  });
}
