architecture-beta
    group opm(cloud)[Owner & Pet Manager]
    group phs(cloud)[Pet Health Service]
    group activity(cloud)[Activity Manager]
    group auth(cloud)[Authentication Service]

    service community(internet)[Community collaborator]

    service opmApi(server)[Owner and Pet API] in opm
    service opmDb(database)[Owner and Pet store] in opm
    service phsApi(server)[Pet Health API] in phs
    service phsDb(database)[Health store] in phs
    service activityApi(server)[Activity and Share API] in activity
    service activityDb(database)[Activity store] in activity
    service authApi(server)[Owner and platform token API] in auth
    service authDb(database)[Owner-session and platform-client store] in auth

    opmApi:B --> T:opmDb
    phsApi:B --> T:phsDb
    activityApi:B --> T:activityDb
    authApi:B --> T:authDb

    phsApi{group}:L --> R:opmApi{group}
    activityApi{group}:L --> R:opmApi{group}
    authApi{group}:L --> R:opmApi{group}

    opmApi{group}:R --> L:authApi{group}
    phsApi{group}:R --> L:authApi{group}
    activityApi{group}:R --> L:authApi{group}

    activityApi{group}:R --> L:phsApi{group}

    opmApi{group}:R --> L:community
    activityApi{group}:R --> L:community
